server:
  port: 8081
  servlet:
    path: /random-food
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.79.207.154:3306/w-paper?useSSL=false
    username: root
    password: tjc159753
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true



